version: 1
disable_existing_loggers: True
compact: False

formatters:
  simple:  &formatter_base
    format: '{message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
  extended:
    <<: *formatter_base
    format: '{asctime}.{msecs:0<3.0f} | [{levelname:>8.8}] {funcName:<40.40} [{lineno:>4}] | {message}'
  extended_colour:
    <<: *formatter_base
    format: '\33[91m{asctime}.{msecs:0<3.0f}\33[0m | [\33[92m{levelname:>8.8}\33[0m] \33[1;96m{funcName:<40.40}\33[0m [\33[95m{lineno:>4}\33[0m] | {message}'

filters:
  console:
    (): "syncify.shared.logger.LogConsoleFilter"
    module_width: 40
  file:
    (): "syncify.shared.logger.LogFileFilter"
    module_width: 40

handlers:
  console_debug: &console
    class: logging.StreamHandler
    level: DEBUG
    formatter: extended_colour
    filters: ["console"]
    stream: ext://sys.stdout

  console_stat:
    <<: *console
    level: STAT

  console_report:
    <<: *console
    level: REPORT

  console_info:
    <<: *console
    level: INFO_EXTRA

  console_simple:
    class: logging.StreamHandler
    level: STAT
    formatter: simple
    filters: ["console"]
    stream: ext://sys.stdout

  file:
    class: syncify.shared.logger.CurrentTimeRotatingFileHandler
    level: DEBUG
    formatter: extended
    filters: ["file"]
    filename: '_logs/{}.log'
    encoding: "utf-8"
    delay: True
    when: "m"
    interval: 2
    count: 30

loggers:
  prod:  &logger
    handlers: [console_simple, file]
    level: DEBUG
    propagate: no

  test:
    <<: *logger
    handlers: [console_debug]

  dev:
    <<: *logger
    handlers: [console_debug]

root:
  level: DEBUG
  handlers: [console_debug, file]
