version: 1
disable_existing_loggers: True
compact: False

formatters:
  simple:
    format: '{message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
  extended:
    format: '{asctime}.{msecs:0<3.0f} | [{levelname:>8.8}] {funcName:<40.40} [{lineno:>4}] | {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'
  extended_colour:
    format: '\33[91m{asctime}.{msecs:0<3.0f}\33[0m | [\33[92m{levelname:>8.8}\33[0m] \33[1;96m{funcName:<40.40}\33[0m [\33[95m{lineno:>4}\33[0m] | {message}'
    datefmt: '%Y-%m-%d %H:%M:%S'
    style: '{'

filters:
  console:
    (): "syncify.utils.logger.LogConsoleFilter"
    module_width: 40
  file:
    (): "syncify.utils.logger.LogFileFilter"
    module_width: 40

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: extended_colour
    filters: ["console"]
    stream: ext://sys.stdout

  file:
    class: syncify.utils.logger.CurrentTimeRotatingFileHandler
    level: DEBUG
    formatter: extended
    filters: ["file"]
    filename: 'D:/Coding/syncify/_logs/{dt}.log'
    encoding: "utf-8"
    when: "m"
    interval: 2
    count: 30

loggers:
  syncify.report:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  syncify.abstract.collection:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  syncify.api._authorise:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  syncify.local.collection:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  syncify.processors.match:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  test:
    level: DEBUG
    handlers: [console]
    propagate: no

  prod:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file]
